import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FloatingNavDemo } from "@/components/FloatingNav";

import { HomeIcon} from "@heroicons/react/16/solid";
import { ContactIcon, ContactRoundIcon, InfoIcon } from "lucide-react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navItems = [
  { name: 'Home', link: '/', icon: <HomeIcon className="w-4 h-4" /> },
  { name: 'About', link: '/about', icon: <InfoIcon className="w-4 h-4" /> },
  { name: 'Contact', link: '/contact', icon: <ContactIcon className="w-4 h-4" /> },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div>
            
            <FloatingNavDemo/>
          </div>

        {children}
      </body>
    </html>
  );
}
