import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import NavbarComp from "@/components/navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-50 dark:bg-neutral-900`}
      >
        {/* Navbar Component */}
        <NavbarComp />

        <div className="min-h-screen px-4 py-8">
          {children}
        </div>
      </body>
    </html>
  );
}
